export const LOAD_CURRENT_SUCCESS = "LOAD_CURRENT_SUCCESS";
export const SEARCH_TERM_SUCCESS = "SEARCH_TERM_SUCCESS";
export const SEARCH_TERM_FAILURE = 'SEARCH_TERM_FAILURE';

export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";


export const SPOTIFY_TOKENS = 'SPOTIFY_TOKENS';
export const SPOTIFY_ME_BEGIN = 'SPOTIFY_ME_BEGIN';
export const SPOTIFY_ME_SUCCESS = 'SPOTIFY_ME_SUCCESS';
export const SPOTIFY_ME_FAILURE = 'SPOTIFY_ME_FAILURE';


